image: images.sbgenomics.com/marko_trifunovic/sevenbridges2-ci-docker:v1

stages:
  - build        # Build the R package binaries
  - document     # Generate package documentation using 'roxygen2'
  - check        # Run various checks (linting, coverage) on the codebase
  - sonar        # Perform SonarQube analysis to report code quality
  - deploy       # Deploy the package site using pkgdown

variables:
  IMAGE: dockerhub.sbgenomics.com/$CI_PROJECT_NAME
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library
  RENV_CONFIG_REPOS_OVERRIDE: http://cran.r-project.org
  LIBRARY_NAME: examplePackage

cache:
  key: $CI_JOB_NAME
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

buildbinary:
  stage: build
  script:
    - R -e 'devtools::build(binary = TRUE, vignettes = FALSE)'

documentation:
  stage: document
  script:
    - R -e 'devtools::document()'

lintr:
  stage: check
  script:
    # redirect lintr stdout and stderr to file
    - R -e "install.packages('lintr')"
    - CI="" Rscript -e "lintr::lint_package()" &> lint_output.txt
    # fail if file is not empty
    - if [ -s "lint_output.txt" ]; then exit 1; fi
  artifacts:
    when: on_failure
    paths:
      - lint_output.txt

coverage:
  stage: check
  rules:
    - when: always
  script:
    - Rscript -e "devtools::install(dependencies = FALSE)"
    - Rscript run_cov.R
  artifacts:
    paths:
      - covr_sonarqube.xml

sonar:
  stage: sonar
  dependencies:
     - coverage
  image: emeraldsquad/sonar-scanner:2.2.0
  script:
    - infinity sonar scanner
  allow_failure: true
  only:
    - merge_requests
    - master
    - develop

pages:
  stage: deploy
  script:
  - apt-get update && apt-get install -y pandoc
  - R -e 'devtools::build(binary = TRUE, vignettes = FALSE)'
  - R -e "install.packages('pkgdown')"
  - R -e "pkgdown::build_site()"
  artifacts:
    paths:
    - public
